import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Integrations","description":"","frontmatter":{},"headers":[],"relativePath":"docs/integrations/index.md","filePath":"docs/integrations/index.md"}');
const _sfc_main = { name: "docs/integrations/index.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="integrations" tabindex="-1">Integrations <a class="header-anchor" href="#integrations" aria-label="Permalink to &quot;Integrations&quot;">​</a></h1><p>Domphy works with most JavaScript/TypeScript libraries because it keeps a strict boundary:</p><ul><li>UI is just declarative element objects rendered by <code>ElementNode</code>.</li><li>Reactivity is subscription-based (<code>listener</code>) and can be connected to any external store/event source.</li><li>State architecture is not owned by Domphy.</li></ul><p>See related references:</p><ul><li><a href="/docs/core/">Core Guide</a></li><li><a href="/docs/core/api/state.html">State API</a></li><li><a href="/docs/core/api/element-node.html">ElementNode API</a></li></ul><h2 id="why-it-works-with-most-js-ts-libraries" tabindex="-1">Why It Works With Most JS/TS Libraries <a class="header-anchor" href="#why-it-works-with-most-js-ts-libraries" aria-label="Permalink to &quot;Why It Works With Most JS/TS Libraries&quot;">​</a></h2><p>Domphy does not force a global app model, router model, or data cache model.<br> If a library can notify changes, it can drive Domphy UI.</p><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">// External store -&gt; Domphy listener</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">store.</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">subscribe</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(() </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> listener</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">())</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">// External stream -&gt; Domphy listener</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">stream.</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">subscribe</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(() </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> listener</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">())</span></span></code></pre></div><p>This keeps integration simple: use your preferred state architecture, and only bridge updates at the view edge.</p><h2 id="boundary-rule-data-and-ui-must-stay-separate" tabindex="-1">Boundary Rule: Data and UI Must Stay Separate <a class="header-anchor" href="#boundary-rule-data-and-ui-must-stay-separate" aria-label="Permalink to &quot;Boundary Rule: Data and UI Must Stay Separate&quot;">​</a></h2><p>Domphy does <strong>not</strong> encourage &quot;plugin islands&quot; for framework-level behavior, especially plugins that combine data/state orchestration with UI behavior.</p><p>Why:</p><ul><li>It increases abstraction layers with little practical value.</li><li>It blurs the boundary between data flow and presentation.</li><li>It makes long-term maintenance harder, especially across teams.</li></ul><p>The author previously built plugin-style integrations (including query/router wrappers), then removed them for this reason: the wrappers added abstraction but reduced clarity around ownership of data vs UI.</p><h2 id="recommended-integration-pattern" tabindex="-1">Recommended Integration Pattern <a class="header-anchor" href="#recommended-integration-pattern" aria-label="Permalink to &quot;Recommended Integration Pattern&quot;">​</a></h2><ol><li>Keep data/state in the external library (query client, router, store, stream, etc.).</li><li>Convert only the minimum needed signals into Domphy-reactive reads at render points.</li><li>Keep patch/component code focused on presentation and interaction.</li></ol><h2 id="examples" tabindex="-1">Examples <a class="header-anchor" href="#examples" aria-label="Permalink to &quot;Examples&quot;">​</a></h2><ul><li><a href="/docs/integrations/i18next.html">i18next</a> — internationalization</li><li><a href="/docs/integrations/tanstack-query.html">TanStack Query</a> — async data fetching and caching</li><li><a href="/docs/integrations/sortablejs.html">SortableJS</a> — drag-and-drop list reordering</li><li><a href="/docs/integrations/zod.html">Zod</a> — form validation</li><li><a href="/docs/integrations/pagejs.html">page.js</a> — client-side routing</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("docs/integrations/index.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const index = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  index as default
};
