import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "@domphy/press";

const here = dirname(fileURLToPath(import.meta.url));

export const config = defineConfig({
  title: "Domphy",
  description:
    "The AI-friendly UI framework — patch-based, framework-agnostic, no virtual DOM.",
  base: "/",
  hostname: "https://domphy.com",
  srcDir: join(here, "docs"),
  outDir: join(here, ".vitepress", "dist"),
  head: [
    `<link rel="icon" href="/favicon.svg">`,
    `<script async src="https://www.googletagmanager.com/gtag/js?id=G-NKPX3DHXWE"></script>`,
    `<script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','G-NKPX3DHXWE');</script>`,
  ],
  themeConfig: {
    footerMessage: 'Released under the MIT License. Made by <a href="https://khanhhuu.com" target="_blank">Nguyen Huu Khanh</a>.',
    nav: [
      { text: "Docs", link: "/docs/" },
      {
        text: "Packages",
        items: [
          { text: "Core", link: "/docs/core/" },
          { text: "Theme", link: "/docs/theme/" },
          { text: "UI", link: "/docs/ui/" },
          { text: "App", link: "/docs/app/" },
          { text: "Query", link: "/docs/query/" },
          { text: "Router", link: "/docs/router/" },
          { text: "Table", link: "/docs/table/" },
          { text: "Virtual", link: "/docs/virtual/" },
          { text: "Form", link: "/docs/form/" },
          { text: "DnD", link: "/docs/dnd/" },
          { text: "Chart", link: "/docs/chart/" },
          { text: "Press", link: "/docs/press/" },
          { text: "Doctor", link: "/docs/doctor/" },
          { text: "MCP", link: "/docs/mcp/" },
          { text: "Palette", link: "/docs/palette/" },
          { text: "i18n", link: "/docs/i18n/" },
          { text: "Markdown", link: "/docs/markdown/" },
          { text: "Mermaid", link: "/docs/mermaid/" },
          { text: "Audit", link: "/docs/audit/" },
        ],
      },
      { text: "AI", link: "/docs/ai" },
      { text: "Playground", link: "/docs/playground" },
    ],
    sidebar: {
      "/docs/core/": [
        { text: "Overview", link: "/docs/core/" },
        { text: "Syntax", link: "/docs/core/syntax" },
        { text: "Reactivity", link: "/docs/core/reactivity" },
        { text: "Lifecycle", link: "/docs/core/lifecycle" },
        { text: "Context & Shared State", link: "/docs/core/context" },
        { text: "Refs & DOM Access", link: "/docs/core/refs" },
        { text: "Error Handling", link: "/docs/core/error-handling" },
        { text: "Performance", link: "/docs/core/performance" },
        { text: "Common Patterns", link: "/docs/core/patterns" },
        { text: "Composing Elements", link: "/docs/core/composing" },
        { text: "TypeScript", link: "/docs/core/typescript" },
        { text: "Testing", link: "/docs/core/testing" },
        { text: "Migration Guide", link: "/docs/core/migration" },
        { text: "SSR", link: "/docs/core/ssr" },
        { text: "Portal", link: "/docs/core/portal" },
        {
          text: "Patterns",
          items: [
            {
              text: "Insert Content",
              link: "/docs/core/patterns/insert-content",
            },
          ],
        },
        {
          text: "API Reference",
          items: [
            { text: "ElementNode", link: "/docs/core/api/element-node" },
            { text: "ElementList", link: "/docs/core/api/element-list" },
            { text: "AttributeList", link: "/docs/core/api/attribute-list" },
            { text: "TextNode", link: "/docs/core/api/text-node" },
            { text: "State", link: "/docs/core/api/state" },
            { text: "Notifier", link: "/docs/core/api/notifier" },
            { text: "Utilities", link: "/docs/core/api/utilities" },
          ],
        },
      ],
      "/docs/theme/": [
        { text: "Overview", link: "/docs/theme/" },
        { text: "Setup", link: "/docs/theme/setup" },
        { text: "Palette", link: "/docs/theme/palette" },
        { text: "Dark Mode", link: "/docs/theme/dark-mode" },
        { text: "Color Roles & Semantic", link: "/docs/theme/color-roles" },
        { text: "Spacing System", link: "/docs/theme/spacing" },
        { text: "Typography", link: "/docs/theme/typography" },
        { text: "Motion & Animation", link: "/docs/theme/motion" },
        { text: "Responsive Design", link: "/docs/theme/responsive" },
        { text: "API", link: "/docs/theme/api" },
        {
          text: "Theory",
          items: [
            { text: "Tone", link: "/docs/theme/tone" },
            { text: "Size", link: "/docs/theme/size" },
          ],
        },
      ],
      "/docs/ui/": [
        { text: "Overview", link: "/docs/ui/" },
        { text: "Color And Tone", link: "/docs/ui/color" },
        { text: "Dimension", link: "/docs/ui/dimension" },
        { text: "Customization", link: "/docs/ui/customization" },
        { text: "Creation", link: "/docs/ui/creation" },
        {
          text: "Patches",
          items: [
            { text: "Abbreviation", link: "/docs/ui/patches/abbreviation" },
            { text: "Alert", link: "/docs/ui/patches/alert" },
            { text: "Avatar", link: "/docs/ui/patches/avatar" },
            { text: "Badge", link: "/docs/ui/patches/badge" },
            { text: "Blockquote", link: "/docs/ui/patches/blockquote" },
            { text: "Breadcrumb", link: "/docs/ui/patches/breadcrumb" },
            {
              text: "Breadcrumb Ellipsis",
              link: "/docs/ui/patches/breadcrumb-ellipsis",
            },
            { text: "Button", link: "/docs/ui/patches/button" },
            { text: "Button Ghost", link: "/docs/ui/patches/button-ghost" },
            { text: "Button Switch", link: "/docs/ui/patches/button-switch" },
            { text: "Card", link: "/docs/ui/patches/card" },
            { text: "Code", link: "/docs/ui/patches/code" },
            { text: "Combobox", link: "/docs/ui/patches/combobox" },
            { text: "Command", link: "/docs/ui/patches/command" },
            { text: "Date Picker", link: "/docs/ui/patches/date-picker" },
            {
              text: "Description List",
              link: "/docs/ui/patches/description-list",
            },
            { text: "Accordion", link: "/docs/ui/patches/accordion" },
            { text: "Details", link: "/docs/ui/patches/details" },
            { text: "Dialog", link: "/docs/ui/patches/dialog" },
            { text: "Divider", link: "/docs/ui/patches/divider" },
            { text: "Drawer", link: "/docs/ui/patches/drawer" },
            { text: "Empty", link: "/docs/ui/patches/empty" },
            { text: "Emphasis", link: "/docs/ui/patches/emphasis" },
            { text: "Error Boundary", link: "/docs/ui/patches/error-boundary" },
            { text: "Figure", link: "/docs/ui/patches/figure" },
            { text: "Form Group", link: "/docs/ui/patches/form-group" },
            { text: "Heading", link: "/docs/ui/patches/heading" },
            {
              text: "Horizontal Rule",
              link: "/docs/ui/patches/horizontal-rule",
            },
            { text: "Icon", link: "/docs/ui/patches/icon" },
            { text: "Image", link: "/docs/ui/patches/image" },
            { text: "Input Checkbox", link: "/docs/ui/patches/input-checkbox" },
            { text: "Input Color", link: "/docs/ui/patches/input-color" },
            {
              text: "Input Date Time",
              link: "/docs/ui/patches/input-date-time",
            },
            { text: "Input File", link: "/docs/ui/patches/input-file" },
            { text: "Input Number", link: "/docs/ui/patches/input-number" },
            { text: "Input OTP", link: "/docs/ui/patches/input-otp" },
            {
              text: "Input Password",
              link: "/docs/ui/patches/input-password",
            },
            { text: "Input Radio", link: "/docs/ui/patches/input-radio" },
            { text: "Input Range", link: "/docs/ui/patches/input-range" },
            { text: "Input Search", link: "/docs/ui/patches/input-search" },
            { text: "Input Switch", link: "/docs/ui/patches/input-switch" },
            { text: "Input Text", link: "/docs/ui/patches/input-text" },
            { text: "Keyboard", link: "/docs/ui/patches/keyboard" },
            { text: "FAB", link: "/docs/ui/patches/fab" },
            { text: "Label", link: "/docs/ui/patches/label" },
            { text: "Link", link: "/docs/ui/patches/link" },
            { text: "List", link: "/docs/ui/patches/list" },
            { text: "Mark", link: "/docs/ui/patches/mark" },
            { text: "Menu", link: "/docs/ui/patches/menu" },
            { text: "Menu Item", link: "/docs/ui/patches/menu-item" },
            { text: "Motion", link: "/docs/ui/patches/motion" },
            { text: "Ordered List", link: "/docs/ui/patches/ordered-list" },
            { text: "Pagination", link: "/docs/ui/patches/pagination" },
            { text: "Paragraph", link: "/docs/ui/patches/paragraph" },
            { text: "Popover", link: "/docs/ui/patches/popover" },
            { text: "Popover Arrow", link: "/docs/ui/patches/popover-arrow" },
            { text: "Preformated", link: "/docs/ui/patches/preformated" },
            { text: "Progress", link: "/docs/ui/patches/progress" },
            { text: "Rating", link: "/docs/ui/patches/rating" },
            { text: "Ring Progress", link: "/docs/ui/patches/ring-progress" },
            { text: "Scroll Area", link: "/docs/ui/patches/scroll-area" },
            { text: "Segmented", link: "/docs/ui/patches/segmented" },
            { text: "Segmented Item", link: "/docs/ui/patches/segmented-item" },
            { text: "Select", link: "/docs/ui/patches/select" },
            { text: "Select Box", link: "/docs/ui/patches/select-box" },
            { text: "Select Item", link: "/docs/ui/patches/select-item" },
            { text: "Select List", link: "/docs/ui/patches/select-list" },
            { text: "Skeleton", link: "/docs/ui/patches/skeleton" },
            { text: "Small", link: "/docs/ui/patches/small" },
            { text: "Spinner", link: "/docs/ui/patches/spinner" },
            { text: "Splitter", link: "/docs/ui/patches/splitter" },
            { text: "Steps", link: "/docs/ui/patches/steps" },
            { text: "Step Item", link: "/docs/ui/patches/step-item" },
            { text: "Strong", link: "/docs/ui/patches/strong" },
            { text: "Subscript", link: "/docs/ui/patches/subscript" },
            { text: "Superscript", link: "/docs/ui/patches/superscript" },
            { text: "Table", link: "/docs/ui/patches/table" },
            { text: "Tab", link: "/docs/ui/patches/tab" },
            { text: "Tab Panel", link: "/docs/ui/patches/tab-panel" },
            { text: "Tabs", link: "/docs/ui/patches/tabs" },
            { text: "Tag", link: "/docs/ui/patches/tag" },
            { text: "Textarea", link: "/docs/ui/patches/textarea" },
            { text: "Timeline", link: "/docs/ui/patches/timeline" },
            { text: "Toast", link: "/docs/ui/patches/toast" },
            { text: "Toggle", link: "/docs/ui/patches/toggle" },
            { text: "Toggle Group", link: "/docs/ui/patches/toggle-group" },
            { text: "Toolbar", link: "/docs/ui/patches/toolbar" },
            { text: "Tooltip", link: "/docs/ui/patches/tooltip" },
            {
              text: "TransitionGroup",
              link: "/docs/ui/patches/transition-group",
            },
            { text: "Typography", link: "/docs/ui/patches/typography" },
            { text: "Unordered List", link: "/docs/ui/patches/unordered-list" },
          ],
        },
        {
          text: "Recipes",
          items: [
            { text: "Alert Dialog", link: "/docs/ui/recipes/alertDialog" },
            { text: "Collapsible", link: "/docs/ui/recipes/collapsible" },
            { text: "Context Menu", link: "/docs/ui/recipes/contextMenu" },
            { text: "Hover Card", link: "/docs/ui/recipes/hoverCard" },
            { text: "Menubar", link: "/docs/ui/recipes/menuBar" },
          ],
        },
      ],
      "/docs/query/": [
        { text: "Overview", link: "/docs/query/" },
        { text: "Domphy Adapter", link: "/docs/query/adapter" },
        { text: "Queries", link: "/docs/query/queries" },
        { text: "Mutations", link: "/docs/query/mutations" },
        { text: "Parallel & Dependent", link: "/docs/query/parallel" },
        { text: "Caching", link: "/docs/query/caching" },
        { text: "Infinite Queries", link: "/docs/query/infinite-queries" },
        { text: "Polling & Window Focus", link: "/docs/query/polling" },
        { text: "Query Invalidation", link: "/docs/query/invalidation" },
        { text: "Testing", link: "/docs/query/testing" },
        { text: "Suspense & Streaming", link: "/docs/query/suspense" },
        { text: "SSR & Hydration", link: "/docs/query/ssr" },
        { text: "Advanced Patterns", link: "/docs/query/advanced" },
        { text: "TypeScript", link: "/docs/query/typescript" },
        { text: "Devtools", link: "/docs/query/devtools" },
        { text: "API Reference", link: "/docs/query/api" },
      ],
      "/docs/router/": [
        { text: "Overview", link: "/docs/router/" },
        { text: "Routes", link: "/docs/router/routes" },
        { text: "Navigation", link: "/docs/router/navigation" },
        { text: "Search Params", link: "/docs/router/search-params" },
        { text: "Data Loading", link: "/docs/router/data-loading" },
        { text: "Data Mutations", link: "/docs/router/data-mutations" },
        { text: "Code Splitting", link: "/docs/router/lazy-loading" },
        { text: "Authentication", link: "/docs/router/authentication" },
        { text: "Error Handling", link: "/docs/router/error-handling" },
        {
          text: "Navigation Blocking",
          link: "/docs/router/navigation-blocking",
        },
        { text: "Router Context", link: "/docs/router/router-context" },
        { text: "Type Safety", link: "/docs/router/type-safety" },
        { text: "Scroll Restoration", link: "/docs/router/scroll-restoration" },
        { text: "SSR", link: "/docs/router/ssr" },
        { text: "API Reference", link: "/docs/router/api" },
      ],
      "/docs/table/": [
        { text: "Overview", link: "/docs/table/" },
        { text: "Domphy Adapter", link: "/docs/table/adapter" },
        { text: "Columns & Row Models", link: "/docs/table/columns" },
        { text: "Sorting & Filtering", link: "/docs/table/sorting-filtering" },
        {
          text: "Pagination & Selection",
          link: "/docs/table/pagination-selection",
        },
        { text: "Advanced Features", link: "/docs/table/advanced" },
        { text: "Column Groups & Headers", link: "/docs/table/column-groups" },
        { text: "Grouping & Expanding", link: "/docs/table/grouping" },
        {
          text: "Column Visibility & Ordering",
          link: "/docs/table/column-visibility",
        },
        { text: "Faceting & Filter UI", link: "/docs/table/faceting" },
        { text: "Row Pinning", link: "/docs/table/row-pinning" },
        { text: "Custom Features", link: "/docs/table/custom-features" },
        { text: "Virtualization", link: "/docs/table/virtualization" },
        { text: "API Reference", link: "/docs/table/api" },
      ],
      "/docs/virtual/": [
        { text: "Overview", link: "/docs/virtual/" },
        { text: "Usage Patterns", link: "/docs/virtual/usage" },
        { text: "Infinite Scroll", link: "/docs/virtual/infinite-scroll" },
        { text: "Grid Virtualization", link: "/docs/virtual/grid" },
        { text: "API Reference", link: "/docs/virtual/api" },
        { text: "Scroll Navigation", link: "/docs/virtual/scroll-to" },
        { text: "Dynamic Sizes", link: "/docs/virtual/dynamic-sizes" },
        { text: "Masonry Layout", link: "/docs/virtual/masonry" },
        {
          text: "Window Virtualizer",
          link: "/docs/virtual/window-virtualizer",
        },
      ],
      "/docs/form/": [
        { text: "Overview", link: "/docs/form/" },
        { text: "Core Concepts", link: "/docs/form/concepts" },
        { text: "Validation", link: "/docs/form/validation" },
        { text: "Field Arrays", link: "/docs/form/arrays" },
        { text: "Submission & Async", link: "/docs/form/submission" },
        { text: "Listeners & Side Effects", link: "/docs/form/listeners" },
        { text: "Async Initial Values", link: "/docs/form/async-values" },
        { text: "TypeScript", link: "/docs/form/typescript" },
        { text: "UI Patches & Form Fields", link: "/docs/form/ui-integration" },
        { text: "Devtools", link: "/docs/form/devtools" },
        { text: "Form Composition", link: "/docs/form/composition" },
        { text: "Testing Forms", link: "/docs/form/testing" },
        { text: "SSR & Hydration", link: "/docs/form/ssr" },
        { text: "Linked Fields", link: "/docs/form/linked-fields" },
      ],
      "/docs/dnd/": [
        { text: "Overview", link: "/docs/dnd/" },
        { text: "API Reference", link: "/docs/dnd/api" },
        { text: "Sortable List", link: "/docs/dnd/sortable" },
        { text: "Multi-Container", link: "/docs/dnd/multi-container" },
        { text: "Multi-Drag", link: "/docs/dnd/multi-drag" },
        { text: "Animations", link: "/docs/dnd/animations" },
        {
          text: "Handles & Filtering",
          link: "/docs/dnd/handles-and-filtering",
        },
        { text: "Accessibility", link: "/docs/dnd/accessibility" },
      ],
      "/docs/doctor/": [
        { text: "Overview", link: "/docs/doctor/" },
        { text: "Rules Reference", link: "/docs/doctor/rules" },
        { text: "Configuration & API", link: "/docs/doctor/configuration" },
        { text: "Agent Loop", link: "/docs/doctor/agent-loop" },
      ],
      "/docs/audit/": [
        { text: "Overview", link: "/docs/audit/" },
        {
          text: "Interpreting Audit Results",
          link: "/docs/audit/interpreting-results",
        },
        { text: "CI Integration", link: "/docs/audit/ci-integration" },
        { text: "checkLayout API", link: "/docs/audit/check-layout" },
      ],
      "/docs/palette/": [
        { text: "Overview", link: "/docs/palette/" },
        { text: "Paper — Measuring Quality", link: "/docs/palette/measuring" },
        { text: "Ramp", link: "/docs/palette/ramp" },
        {
          text: "Accessibility & Contrast",
          link: "/docs/palette/accessibility",
        },
        { text: "Swatch & Color Utilities", link: "/docs/palette/swatch" },
      ],
      "/docs/app/": [
        { text: "Overview", link: "/docs/app/" },
        { text: "Routing", link: "/docs/app/routing" },
        { text: "Layouts & Boundaries", link: "/docs/app/layouts" },
        { text: "Navigation", link: "/docs/app/navigation" },
        { text: "Data Fetching", link: "/docs/app/data-fetching" },
        { text: "Metadata", link: "/docs/app/metadata" },
        { text: "Middleware", link: "/docs/app/middleware" },
        { text: "SSR & Hydration", link: "/docs/app/ssr" },
        { text: "API Routes", link: "/docs/app/api-routes" },
        { text: "Image & Script", link: "/docs/app/assets" },
        { text: "i18n Routing", link: "/docs/app/i18n" },
        { text: "API Reference", link: "/docs/app/api" },
      ],
      "/docs/markdown/": [
        { text: "Overview", link: "/docs/markdown/" },
        { text: "Frontmatter", link: "/docs/markdown/frontmatter" },
        { text: "Syntax Reference", link: "/docs/markdown/syntax-reference" },
        { text: "Syntax Highlighting", link: "/docs/markdown/highlighting" },
        { text: "Table of Contents", link: "/docs/markdown/table-of-contents" },
      ],
      "/docs/mermaid/": [
        { text: "Overview", link: "/docs/mermaid/" },
        { text: "Supported Diagrams", link: "/docs/mermaid/diagrams" },
        { text: "Configuration & Themes", link: "/docs/mermaid/configuration" },
        { text: "Flowchart", link: "/docs/mermaid/flowchart" },
        { text: "Sequence Diagrams", link: "/docs/mermaid/sequence" },
        { text: "Class & State Diagrams", link: "/docs/mermaid/class-diagram" },
        {
          text: "ER, Gantt, Pie & Git Graphs",
          link: "/docs/mermaid/er-gantt-pie",
        },
        { text: "Client-Side Rendering", link: "/docs/mermaid/client" },
        { text: "Build-Time Integration", link: "/docs/mermaid/build" },
      ],
      "/docs/floating/": [
        { text: "Getting Started", link: "/docs/floating" },
        { text: "Placement", link: "/docs/floating/placement" },
        { text: "offset", link: "/docs/floating/offset" },
        { text: "flip & autoPlacement", link: "/docs/floating/flip" },
        { text: "shift & limitShift", link: "/docs/floating/shift" },
        { text: "arrow", link: "/docs/floating/arrow" },
        { text: "size", link: "/docs/floating/size" },
        {
          text: "autoUpdate, hide & Virtual Elements",
          link: "/docs/floating/auto-update",
        },
      ],
      "/docs/chart/": [
        { text: "Overview", link: "/docs/chart/" },
        { text: "Series Reference", link: "/docs/chart/series" },
        { text: "Axes & Grid", link: "/docs/chart/axes" },
        { text: "Colors & Theme", link: "/docs/chart/colors" },
        { text: "Marks", link: "/docs/chart/marks" },
        { text: "Interaction & Events", link: "/docs/chart/events" },
        { text: "ChartEngine API", link: "/docs/chart/engine" },
        { text: "vs ECharts", link: "/docs/chart/vs-echarts" },
      ],
      "/docs/i18n/": [
        { text: "Overview", link: "/docs/i18n/" },
        { text: "Setup", link: "/docs/i18n/setup" },
        { text: "Namespaces", link: "/docs/i18n/namespaces" },
        { text: "Pluralization", link: "/docs/i18n/pluralization" },
        { text: "Interpolation & Formatting", link: "/docs/i18n/formatting" },
        { text: "Lazy Loading & Backend", link: "/docs/i18n/backend" },
        { text: "Integration Guide", link: "/docs/i18n/integration" },
        { text: "API Reference", link: "/docs/i18n/api" },
      ],
      "/docs/press/": [
        { text: "Overview", link: "/docs/press/" },
        { text: "Configuration", link: "/docs/press/config" },
        { text: "Routing", link: "/docs/press/routing" },
        { text: "Markdown Features", link: "/docs/press/markdown" },
        { text: "Search", link: "/docs/press/search" },
        { text: "Internationalization", link: "/docs/press/i18n" },
        { text: "Custom Theme & Slots", link: "/docs/press/custom-theme" },
        { text: "Extending Markdown", link: "/docs/press/extending-markdown" },
        { text: "Customization", link: "/docs/press/customization" },
        { text: "Deploying", link: "/docs/press/deploy" },
        { text: "Programmatic API", link: "/docs/press/api" },
      ],
      "/docs/mcp/": [
        { text: "Overview", link: "/docs/mcp/" },
        { text: "Tools Reference", link: "/docs/mcp/tools" },
      ],
      "/docs/integrations/": [
        { text: "Guide", link: "/docs/integrations/" },
        {
          text: "Example",
          items: [
            { text: "Chart.js", link: "/docs/integrations/chartjs" },
            { text: "SortableJS", link: "/docs/integrations/sortablejs" },
            { text: "Zod", link: "/docs/integrations/zod" },
            { text: "page.js", link: "/docs/integrations/pagejs" },
          ],
        },
      ],
      "/docs/guide/": [
        { text: "Why Domphy", link: "/docs/guide/why-domphy" },
        { text: "Coming from React", link: "/docs/guide/from-react" },
      ],
      "/docs/research/": [{ text: "Research", link: "/docs/research/" }],
      "/docs/showcases/": [{ text: "Showcases", link: "/docs/showcases/" }],
      "/docs/": [
        { text: "Overview", link: "/docs/" },
        { text: "Quickstart", link: "/docs/quickstart" },
        {
          text: "Guide",
          items: [
            { text: "Why Domphy", link: "/docs/guide/why-domphy" },
            { text: "Coming from React", link: "/docs/guide/from-react" },
          ],
        },
        { text: "Core", link: "/docs/core/" },
        { text: "Theme", link: "/docs/theme/" },
        { text: "UI", link: "/docs/ui/" },
        { text: "Query", link: "/docs/query/" },
        { text: "Router", link: "/docs/router/" },
        { text: "Table", link: "/docs/table/" },
        { text: "Virtual", link: "/docs/virtual/" },
        { text: "Form", link: "/docs/form/" },
        { text: "DnD", link: "/docs/dnd/" },
        { text: "Palette", link: "/docs/palette/" },
        { text: "App", link: "/docs/app/" },
        { text: "Doctor", link: "/docs/doctor/" },
        { text: "Audit", link: "/docs/audit/" },
        { text: "i18n", link: "/docs/i18n/" },
        { text: "Press", link: "/docs/press/" },
        { text: "MCP", link: "/docs/mcp/" },
        { text: "Integrations", link: "/docs/integrations/" },
        { text: "Research", link: "/docs/research/" },
        { text: "Showcases", link: "/docs/showcases/" },
        { text: "Playground", link: "/docs/playground" },
      ],
    },
  },
});
