// AUTO-GENERATED by scripts/gen-visual-blocks.mjs — do not edit by hand.
// Re-run: pnpm --filter domphy-web visual:blocks-gen  (or node scripts/gen-visual-blocks.mjs)
import { visualCell, visualSection, visualPage } from "./cell.js";

import demo_android from "../blocks/android.js";
import demo_animatedBeam from "../blocks/animatedBeam.js";
import demo_animatedCircularProgressBar from "../blocks/animatedCircularProgressBar.js";
import demo_animatedGradientText from "../blocks/animatedGradientText.js";
import demo_animatedGridPattern from "../blocks/animatedGridPattern.js";
import demo_animatedList from "../blocks/animatedList.js";
import demo_animatedShinyText from "../blocks/animatedShinyText.js";
import demo_animatedThemeToggler from "../blocks/animatedThemeToggler.js";
import demo_auroraText from "../blocks/auroraText.js";
import demo_avatarCircles from "../blocks/avatarCircles.js";
import demo_backlight from "../blocks/backlight.js";
import demo_bentoGrid from "../blocks/bentoGrid.js";
import demo_blurFade from "../blocks/blurFade.js";
import demo_borderBeam from "../blocks/borderBeam.js";
import demo_chartAreaAxes from "../blocks/chartAreaAxes.js";
import demo_chartAreaDefault from "../blocks/chartAreaDefault.js";
import demo_chartAreaGradient from "../blocks/chartAreaGradient.js";
import demo_chartAreaIcons from "../blocks/chartAreaIcons.js";
import demo_chartAreaInteractive from "../blocks/chartAreaInteractive.js";
import demo_chartAreaLegend from "../blocks/chartAreaLegend.js";
import demo_chartAreaLinear from "../blocks/chartAreaLinear.js";
import demo_chartAreaStacked from "../blocks/chartAreaStacked.js";
import demo_chartAreaStackedExpand from "../blocks/chartAreaStackedExpand.js";
import demo_chartAreaStep from "../blocks/chartAreaStep.js";
import demo_chartBarActive from "../blocks/chartBarActive.js";
import demo_chartBarDefault from "../blocks/chartBarDefault.js";
import demo_chartBarHorizontal from "../blocks/chartBarHorizontal.js";
import demo_chartBarInteractive from "../blocks/chartBarInteractive.js";
import demo_chartBarLabel from "../blocks/chartBarLabel.js";
import demo_chartBarLabelCustom from "../blocks/chartBarLabelCustom.js";
import demo_chartBarMixed from "../blocks/chartBarMixed.js";
import demo_chartBarMultiple from "../blocks/chartBarMultiple.js";
import demo_chartBarNegative from "../blocks/chartBarNegative.js";
import demo_chartBarStacked from "../blocks/chartBarStacked.js";
import demo_chartLineDefault from "../blocks/chartLineDefault.js";
import demo_chartLineDots from "../blocks/chartLineDots.js";
import demo_chartLineDotsColors from "../blocks/chartLineDotsColors.js";
import demo_chartLineDotsCustom from "../blocks/chartLineDotsCustom.js";
import demo_chartLineInteractive from "../blocks/chartLineInteractive.js";
import demo_chartLineLabel from "../blocks/chartLineLabel.js";
import demo_chartLineLabelCustom from "../blocks/chartLineLabelCustom.js";
import demo_chartLineLinear from "../blocks/chartLineLinear.js";
import demo_chartLineMultiple from "../blocks/chartLineMultiple.js";
import demo_chartLineStep from "../blocks/chartLineStep.js";
import demo_chartPieDonut from "../blocks/chartPieDonut.js";
import demo_chartPieDonutActive from "../blocks/chartPieDonutActive.js";
import demo_chartPieDonutText from "../blocks/chartPieDonutText.js";
import demo_chartPieInteractive from "../blocks/chartPieInteractive.js";
import demo_chartPieLabel from "../blocks/chartPieLabel.js";
import demo_chartPieLabelCustom from "../blocks/chartPieLabelCustom.js";
import demo_chartPieLabelList from "../blocks/chartPieLabelList.js";
import demo_chartPieLegend from "../blocks/chartPieLegend.js";
import demo_chartPieSeparatorNone from "../blocks/chartPieSeparatorNone.js";
import demo_chartPieSimple from "../blocks/chartPieSimple.js";
import demo_chartPieStacked from "../blocks/chartPieStacked.js";
import demo_chartRadarDefault from "../blocks/chartRadarDefault.js";
import demo_chartRadarDots from "../blocks/chartRadarDots.js";
import demo_chartRadarGrid from "../blocks/chartRadarGrid.js";
import demo_chartRadarGridCircle from "../blocks/chartRadarGridCircle.js";
import demo_chartRadarGridCircleFill from "../blocks/chartRadarGridCircleFill.js";
import demo_chartRadarGridCustom from "../blocks/chartRadarGridCustom.js";
import demo_chartRadarGridFill from "../blocks/chartRadarGridFill.js";
import demo_chartRadarGridNone from "../blocks/chartRadarGridNone.js";
import demo_chartRadarIcons from "../blocks/chartRadarIcons.js";
import demo_chartRadarLabelCustom from "../blocks/chartRadarLabelCustom.js";
import demo_chartRadarLegend from "../blocks/chartRadarLegend.js";
import demo_chartRadarLinesOnly from "../blocks/chartRadarLinesOnly.js";
import demo_chartRadarMultiple from "../blocks/chartRadarMultiple.js";
import demo_chartRadarRadius from "../blocks/chartRadarRadius.js";
import demo_chartRadialGrid from "../blocks/chartRadialGrid.js";
import demo_chartRadialLabel from "../blocks/chartRadialLabel.js";
import demo_chartRadialShape from "../blocks/chartRadialShape.js";
import demo_chartRadialSimple from "../blocks/chartRadialSimple.js";
import demo_chartRadialStacked from "../blocks/chartRadialStacked.js";
import demo_chartRadialText from "../blocks/chartRadialText.js";
import demo_chartTooltipAdvanced from "../blocks/chartTooltipAdvanced.js";
import demo_chartTooltipDefault from "../blocks/chartTooltipDefault.js";
import demo_chartTooltipFormatter from "../blocks/chartTooltipFormatter.js";
import demo_chartTooltipIcons from "../blocks/chartTooltipIcons.js";
import demo_chartTooltipIndicatorLine from "../blocks/chartTooltipIndicatorLine.js";
import demo_chartTooltipIndicatorNone from "../blocks/chartTooltipIndicatorNone.js";
import demo_chartTooltipLabelCustom from "../blocks/chartTooltipLabelCustom.js";
import demo_chartTooltipLabelFormatter from "../blocks/chartTooltipLabelFormatter.js";
import demo_chartTooltipLabelNone from "../blocks/chartTooltipLabelNone.js";
import demo_codeComparison from "../blocks/codeComparison.js";
import demo_comicText from "../blocks/comicText.js";
import demo_confetti from "../blocks/confetti.js";
import demo_confettiButton from "../blocks/confettiButton.js";
import demo_coolMode from "../blocks/coolMode.js";
import demo_dashboard01 from "../blocks/dashboard01.js";
import demo_diaTextReveal from "../blocks/diaTextReveal.js";
import demo_dock from "../blocks/dock.js";
import demo_dotPattern from "../blocks/dotPattern.js";
import demo_dottedMap from "../blocks/dottedMap.js";
import demo_fileTree from "../blocks/fileTree.js";
import demo_flickeringGrid from "../blocks/flickeringGrid.js";
import demo_glareHover from "../blocks/glareHover.js";
import demo_globe from "../blocks/globe.js";
import demo_gridPattern from "../blocks/gridPattern.js";
import demo_heroVideoDialog from "../blocks/heroVideoDialog.js";
import demo_hexagonPattern from "../blocks/hexagonPattern.js";
import demo_hyperText from "../blocks/hyperText.js";
import demo_iconCloud from "../blocks/iconCloud.js";
import demo_interactiveGridPattern from "../blocks/interactiveGridPattern.js";
import demo_interactiveHoverButton from "../blocks/interactiveHoverButton.js";
import demo_iphone from "../blocks/iphone.js";
import demo_kineticText from "../blocks/kineticText.js";
import demo_lens from "../blocks/lens.js";
import demo_lightRays from "../blocks/lightRays.js";
import demo_lineShadowText from "../blocks/lineShadowText.js";
import demo_Login01 from "../blocks/Login01.js";
import demo_Login02 from "../blocks/Login02.js";
import demo_Login03 from "../blocks/Login03.js";
import demo_Login04 from "../blocks/Login04.js";
import demo_Login05 from "../blocks/Login05.js";
import demo_magicCard from "../blocks/magicCard.js";
import demo_marquee from "../blocks/marquee.js";
import demo_meteors from "../blocks/meteors.js";
import demo_morphingText from "../blocks/morphingText.js";
import demo_neonGradientCard from "../blocks/neonGradientCard.js";
import demo_noiseTexture from "../blocks/noiseTexture.js";
import demo_numberTicker from "../blocks/numberTicker.js";
import demo_orbitingCircles from "../blocks/orbitingCircles.js";
import demo_particles from "../blocks/particles.js";
import demo_pixelImage from "../blocks/pixelImage.js";
import demo_pointer from "../blocks/pointer.js";
import demo_progressiveBlur from "../blocks/progressiveBlur.js";
import demo_pulsatingButton from "../blocks/pulsatingButton.js";
import demo_rainbowButton from "../blocks/rainbowButton.js";
import demo_retroGrid from "../blocks/retroGrid.js";
import demo_ripple from "../blocks/ripple.js";
import demo_rippleButton from "../blocks/rippleButton.js";
import demo_safari from "../blocks/safari.js";
import demo_scrollBasedVelocity from "../blocks/scrollBasedVelocity.js";
import demo_scrollProgress from "../blocks/scrollProgress.js";
import demo_shimmerButton from "../blocks/shimmerButton.js";
import demo_shineBorder from "../blocks/shineBorder.js";
import demo_shinyButton from "../blocks/shinyButton.js";
import demo_sidebar01 from "../blocks/sidebar01.js";
import demo_sidebar02 from "../blocks/sidebar02.js";
import demo_sidebar03 from "../blocks/sidebar03.js";
import demo_sidebar04 from "../blocks/sidebar04.js";
import demo_sidebar05 from "../blocks/sidebar05.js";
import demo_sidebar06 from "../blocks/sidebar06.js";
import demo_sidebar07 from "../blocks/sidebar07.js";
import demo_sidebar08 from "../blocks/sidebar08.js";
import demo_sidebar09 from "../blocks/sidebar09.js";
import demo_sidebar10 from "../blocks/sidebar10.js";
import demo_sidebar11 from "../blocks/sidebar11.js";
import demo_sidebar12 from "../blocks/sidebar12.js";
import demo_sidebarInDialog from "../blocks/sidebarInDialog.js";
import demo_sidebarLeftRight from "../blocks/sidebarLeftRight.js";
import demo_sidebarOnRight from "../blocks/sidebarOnRight.js";
import demo_sidebarStickyHeader from "../blocks/sidebarStickyHeader.js";
import demo_signup01 from "../blocks/signup01.js";
import demo_signup02 from "../blocks/signup02.js";
import demo_signup03 from "../blocks/signup03.js";
import demo_signup04 from "../blocks/signup04.js";
import demo_signup05 from "../blocks/signup05.js";
import demo_smoothCursor from "../blocks/smoothCursor.js";
import demo_sparklesText from "../blocks/sparklesText.js";
import demo_spinningText from "../blocks/spinningText.js";
import demo_stripedPattern from "../blocks/stripedPattern.js";
import demo_terminal from "../blocks/terminal.js";
import demo_text3dFlip from "../blocks/text3dFlip.js";
import demo_textAnimate from "../blocks/textAnimate.js";
import demo_textHighlighter from "../blocks/textHighlighter.js";
import demo_textReveal from "../blocks/textReveal.js";
import demo_tweetCard from "../blocks/tweetCard.js";
import demo_typingAnimation from "../blocks/typingAnimation.js";
import demo_videoText from "../blocks/videoText.js";
import demo_warpBackground from "../blocks/warpBackground.js";
import demo_wordRotate from "../blocks/wordRotate.js";

export default visualPage("Blocks", [
  visualSection("Components", [
    visualCell("block-android", "android", demo_android),
    visualCell("block-animatedCircularProgressBar", "animatedCircularProgressBar", demo_animatedCircularProgressBar),
    visualCell("block-animatedList", "animatedList", demo_animatedList),
    visualCell("block-avatarCircles", "avatarCircles", demo_avatarCircles),
    visualCell("block-backlight", "backlight", demo_backlight),
    visualCell("block-bentoGrid", "bentoGrid", demo_bentoGrid),
    visualCell("block-codeComparison", "codeComparison", demo_codeComparison),
    visualCell("block-comicText", "comicText", demo_comicText),
    visualCell("block-coolMode", "coolMode", demo_coolMode),
    visualCell("block-dock", "dock", demo_dock),
    visualCell("block-dottedMap", "dottedMap", demo_dottedMap),
    visualCell("block-fileTree", "fileTree", demo_fileTree),
    visualCell("block-globe", "globe", demo_globe),
    visualCell("block-heroVideoDialog", "heroVideoDialog", demo_heroVideoDialog),
    visualCell("block-iconCloud", "iconCloud", demo_iconCloud),
    visualCell("block-interactiveHoverButton", "interactiveHoverButton", demo_interactiveHoverButton),
    visualCell("block-iphone", "iphone", demo_iphone),
    visualCell("block-kineticText", "kineticText", demo_kineticText),
    visualCell("block-lens", "lens", demo_lens),
    visualCell("block-marquee", "marquee", demo_marquee),
    visualCell("block-neonGradientCard", "neonGradientCard", demo_neonGradientCard),
    visualCell("block-orbitingCircles", "orbitingCircles", demo_orbitingCircles),
    visualCell("block-pixelImage", "pixelImage", demo_pixelImage),
    visualCell("block-pointer", "pointer", demo_pointer),
    visualCell("block-progressiveBlur", "progressiveBlur", demo_progressiveBlur),
    visualCell("block-pulsatingButton", "pulsatingButton", demo_pulsatingButton),
    visualCell("block-rainbowButton", "rainbowButton", demo_rainbowButton),
    visualCell("block-rippleButton", "rippleButton", demo_rippleButton),
    visualCell("block-safari", "safari", demo_safari),
    visualCell("block-scrollProgress", "scrollProgress", demo_scrollProgress),
    visualCell("block-shimmerButton", "shimmerButton", demo_shimmerButton),
    visualCell("block-shinyButton", "shinyButton", demo_shinyButton),
    visualCell("block-smoothCursor", "smoothCursor", demo_smoothCursor),
    visualCell("block-terminal", "terminal", demo_terminal),
    visualCell("block-tweetCard", "tweetCard", demo_tweetCard),
    visualCell("block-warpBackground", "warpBackground", demo_warpBackground),
  ]),
  visualSection("Effects", [
    visualCell("block-animatedBeam", "animatedBeam", demo_animatedBeam),
    visualCell("block-animatedGradientText", "animatedGradientText", demo_animatedGradientText),
    visualCell("block-animatedGridPattern", "animatedGridPattern", demo_animatedGridPattern),
    visualCell("block-animatedShinyText", "animatedShinyText", demo_animatedShinyText),
    visualCell("block-animatedThemeToggler", "animatedThemeToggler", demo_animatedThemeToggler),
    visualCell("block-auroraText", "auroraText", demo_auroraText),
    visualCell("block-blurFade", "blurFade", demo_blurFade),
    visualCell("block-borderBeam", "borderBeam", demo_borderBeam),
    visualCell("block-confetti", "confetti", demo_confetti),
    visualCell("block-confettiButton", "confettiButton", demo_confettiButton),
    visualCell("block-diaTextReveal", "diaTextReveal", demo_diaTextReveal),
    visualCell("block-dotPattern", "dotPattern", demo_dotPattern),
    visualCell("block-flickeringGrid", "flickeringGrid", demo_flickeringGrid),
    visualCell("block-glareHover", "glareHover", demo_glareHover),
    visualCell("block-gridPattern", "gridPattern", demo_gridPattern),
    visualCell("block-hexagonPattern", "hexagonPattern", demo_hexagonPattern),
    visualCell("block-hyperText", "hyperText", demo_hyperText),
    visualCell("block-interactiveGridPattern", "interactiveGridPattern", demo_interactiveGridPattern),
    visualCell("block-lightRays", "lightRays", demo_lightRays),
    visualCell("block-lineShadowText", "lineShadowText", demo_lineShadowText),
    visualCell("block-magicCard", "magicCard", demo_magicCard),
    visualCell("block-meteors", "meteors", demo_meteors),
    visualCell("block-morphingText", "morphingText", demo_morphingText),
    visualCell("block-noiseTexture", "noiseTexture", demo_noiseTexture),
    visualCell("block-numberTicker", "numberTicker", demo_numberTicker),
    visualCell("block-particles", "particles", demo_particles),
    visualCell("block-retroGrid", "retroGrid", demo_retroGrid),
    visualCell("block-ripple", "ripple", demo_ripple),
    visualCell("block-scrollBasedVelocity", "scrollBasedVelocity", demo_scrollBasedVelocity),
    visualCell("block-shineBorder", "shineBorder", demo_shineBorder),
    visualCell("block-sparklesText", "sparklesText", demo_sparklesText),
    visualCell("block-spinningText", "spinningText", demo_spinningText),
    visualCell("block-stripedPattern", "stripedPattern", demo_stripedPattern),
    visualCell("block-text3dFlip", "text3dFlip", demo_text3dFlip),
    visualCell("block-textAnimate", "textAnimate", demo_textAnimate),
    visualCell("block-textHighlighter", "textHighlighter", demo_textHighlighter),
    visualCell("block-textReveal", "textReveal", demo_textReveal),
    visualCell("block-typingAnimation", "typingAnimation", demo_typingAnimation),
    visualCell("block-videoText", "videoText", demo_videoText),
    visualCell("block-wordRotate", "wordRotate", demo_wordRotate),
  ]),
  visualSection("Charts", [
    visualCell("block-chartAreaAxes", "chartAreaAxes", demo_chartAreaAxes),
    visualCell("block-chartAreaDefault", "chartAreaDefault", demo_chartAreaDefault),
    visualCell("block-chartAreaGradient", "chartAreaGradient", demo_chartAreaGradient),
    visualCell("block-chartAreaIcons", "chartAreaIcons", demo_chartAreaIcons),
    visualCell("block-chartAreaInteractive", "chartAreaInteractive", demo_chartAreaInteractive),
    visualCell("block-chartAreaLegend", "chartAreaLegend", demo_chartAreaLegend),
    visualCell("block-chartAreaLinear", "chartAreaLinear", demo_chartAreaLinear),
    visualCell("block-chartAreaStacked", "chartAreaStacked", demo_chartAreaStacked),
    visualCell("block-chartAreaStackedExpand", "chartAreaStackedExpand", demo_chartAreaStackedExpand),
    visualCell("block-chartAreaStep", "chartAreaStep", demo_chartAreaStep),
    visualCell("block-chartBarActive", "chartBarActive", demo_chartBarActive),
    visualCell("block-chartBarDefault", "chartBarDefault", demo_chartBarDefault),
    visualCell("block-chartBarHorizontal", "chartBarHorizontal", demo_chartBarHorizontal),
    visualCell("block-chartBarInteractive", "chartBarInteractive", demo_chartBarInteractive),
    visualCell("block-chartBarLabel", "chartBarLabel", demo_chartBarLabel),
    visualCell("block-chartBarLabelCustom", "chartBarLabelCustom", demo_chartBarLabelCustom),
    visualCell("block-chartBarMixed", "chartBarMixed", demo_chartBarMixed),
    visualCell("block-chartBarMultiple", "chartBarMultiple", demo_chartBarMultiple),
    visualCell("block-chartBarNegative", "chartBarNegative", demo_chartBarNegative),
    visualCell("block-chartBarStacked", "chartBarStacked", demo_chartBarStacked),
    visualCell("block-chartLineDefault", "chartLineDefault", demo_chartLineDefault),
    visualCell("block-chartLineDots", "chartLineDots", demo_chartLineDots),
    visualCell("block-chartLineDotsColors", "chartLineDotsColors", demo_chartLineDotsColors),
    visualCell("block-chartLineDotsCustom", "chartLineDotsCustom", demo_chartLineDotsCustom),
    visualCell("block-chartLineInteractive", "chartLineInteractive", demo_chartLineInteractive),
    visualCell("block-chartLineLabel", "chartLineLabel", demo_chartLineLabel),
    visualCell("block-chartLineLabelCustom", "chartLineLabelCustom", demo_chartLineLabelCustom),
    visualCell("block-chartLineLinear", "chartLineLinear", demo_chartLineLinear),
    visualCell("block-chartLineMultiple", "chartLineMultiple", demo_chartLineMultiple),
    visualCell("block-chartLineStep", "chartLineStep", demo_chartLineStep),
    visualCell("block-chartPieDonut", "chartPieDonut", demo_chartPieDonut),
    visualCell("block-chartPieDonutActive", "chartPieDonutActive", demo_chartPieDonutActive),
    visualCell("block-chartPieDonutText", "chartPieDonutText", demo_chartPieDonutText),
    visualCell("block-chartPieInteractive", "chartPieInteractive", demo_chartPieInteractive),
    visualCell("block-chartPieLabel", "chartPieLabel", demo_chartPieLabel),
    visualCell("block-chartPieLabelCustom", "chartPieLabelCustom", demo_chartPieLabelCustom),
    visualCell("block-chartPieLabelList", "chartPieLabelList", demo_chartPieLabelList),
    visualCell("block-chartPieLegend", "chartPieLegend", demo_chartPieLegend),
    visualCell("block-chartPieSeparatorNone", "chartPieSeparatorNone", demo_chartPieSeparatorNone),
    visualCell("block-chartPieSimple", "chartPieSimple", demo_chartPieSimple),
    visualCell("block-chartPieStacked", "chartPieStacked", demo_chartPieStacked),
    visualCell("block-chartRadarDefault", "chartRadarDefault", demo_chartRadarDefault),
    visualCell("block-chartRadarDots", "chartRadarDots", demo_chartRadarDots),
    visualCell("block-chartRadarGrid", "chartRadarGrid", demo_chartRadarGrid),
    visualCell("block-chartRadarGridCircle", "chartRadarGridCircle", demo_chartRadarGridCircle),
    visualCell("block-chartRadarGridCircleFill", "chartRadarGridCircleFill", demo_chartRadarGridCircleFill),
    visualCell("block-chartRadarGridCustom", "chartRadarGridCustom", demo_chartRadarGridCustom),
    visualCell("block-chartRadarGridFill", "chartRadarGridFill", demo_chartRadarGridFill),
    visualCell("block-chartRadarGridNone", "chartRadarGridNone", demo_chartRadarGridNone),
    visualCell("block-chartRadarIcons", "chartRadarIcons", demo_chartRadarIcons),
    visualCell("block-chartRadarLabelCustom", "chartRadarLabelCustom", demo_chartRadarLabelCustom),
    visualCell("block-chartRadarLegend", "chartRadarLegend", demo_chartRadarLegend),
    visualCell("block-chartRadarLinesOnly", "chartRadarLinesOnly", demo_chartRadarLinesOnly),
    visualCell("block-chartRadarMultiple", "chartRadarMultiple", demo_chartRadarMultiple),
    visualCell("block-chartRadarRadius", "chartRadarRadius", demo_chartRadarRadius),
    visualCell("block-chartRadialGrid", "chartRadialGrid", demo_chartRadialGrid),
    visualCell("block-chartRadialLabel", "chartRadialLabel", demo_chartRadialLabel),
    visualCell("block-chartRadialShape", "chartRadialShape", demo_chartRadialShape),
    visualCell("block-chartRadialSimple", "chartRadialSimple", demo_chartRadialSimple),
    visualCell("block-chartRadialStacked", "chartRadialStacked", demo_chartRadialStacked),
    visualCell("block-chartRadialText", "chartRadialText", demo_chartRadialText),
    visualCell("block-chartTooltipAdvanced", "chartTooltipAdvanced", demo_chartTooltipAdvanced),
    visualCell("block-chartTooltipDefault", "chartTooltipDefault", demo_chartTooltipDefault),
    visualCell("block-chartTooltipFormatter", "chartTooltipFormatter", demo_chartTooltipFormatter),
    visualCell("block-chartTooltipIcons", "chartTooltipIcons", demo_chartTooltipIcons),
    visualCell("block-chartTooltipIndicatorLine", "chartTooltipIndicatorLine", demo_chartTooltipIndicatorLine),
    visualCell("block-chartTooltipIndicatorNone", "chartTooltipIndicatorNone", demo_chartTooltipIndicatorNone),
    visualCell("block-chartTooltipLabelCustom", "chartTooltipLabelCustom", demo_chartTooltipLabelCustom),
    visualCell("block-chartTooltipLabelFormatter", "chartTooltipLabelFormatter", demo_chartTooltipLabelFormatter),
    visualCell("block-chartTooltipLabelNone", "chartTooltipLabelNone", demo_chartTooltipLabelNone),
  ]),
  visualSection("Layouts", [
    visualCell("block-dashboard01", "dashboard01", demo_dashboard01, { minWidth: "360px" }),
    visualCell("block-Login01", "Login01", demo_Login01, { minWidth: "360px" }),
    visualCell("block-Login02", "Login02", demo_Login02, { minWidth: "360px" }),
    visualCell("block-Login03", "Login03", demo_Login03, { minWidth: "360px" }),
    visualCell("block-Login04", "Login04", demo_Login04, { minWidth: "360px" }),
    visualCell("block-Login05", "Login05", demo_Login05, { minWidth: "360px" }),
    visualCell("block-sidebar01", "sidebar01", demo_sidebar01, { minWidth: "360px" }),
    visualCell("block-sidebar02", "sidebar02", demo_sidebar02, { minWidth: "360px" }),
    visualCell("block-sidebar03", "sidebar03", demo_sidebar03, { minWidth: "360px" }),
    visualCell("block-sidebar04", "sidebar04", demo_sidebar04, { minWidth: "360px" }),
    visualCell("block-sidebar05", "sidebar05", demo_sidebar05, { minWidth: "360px" }),
    visualCell("block-sidebar06", "sidebar06", demo_sidebar06, { minWidth: "360px" }),
    visualCell("block-sidebar07", "sidebar07", demo_sidebar07, { minWidth: "360px" }),
    visualCell("block-sidebar08", "sidebar08", demo_sidebar08, { minWidth: "360px" }),
    visualCell("block-sidebar09", "sidebar09", demo_sidebar09, { minWidth: "360px" }),
    visualCell("block-sidebar10", "sidebar10", demo_sidebar10, { minWidth: "360px" }),
    visualCell("block-sidebar11", "sidebar11", demo_sidebar11, { minWidth: "360px" }),
    visualCell("block-sidebar12", "sidebar12", demo_sidebar12, { minWidth: "360px" }),
    visualCell("block-sidebarInDialog", "sidebarInDialog", demo_sidebarInDialog, { minWidth: "360px" }),
    visualCell("block-sidebarLeftRight", "sidebarLeftRight", demo_sidebarLeftRight, { minWidth: "360px" }),
    visualCell("block-sidebarOnRight", "sidebarOnRight", demo_sidebarOnRight, { minWidth: "360px" }),
    visualCell("block-sidebarStickyHeader", "sidebarStickyHeader", demo_sidebarStickyHeader, { minWidth: "360px" }),
    visualCell("block-signup01", "signup01", demo_signup01, { minWidth: "360px" }),
    visualCell("block-signup02", "signup02", demo_signup02, { minWidth: "360px" }),
    visualCell("block-signup03", "signup03", demo_signup03, { minWidth: "360px" }),
    visualCell("block-signup04", "signup04", demo_signup04, { minWidth: "360px" }),
    visualCell("block-signup05", "signup05", demo_signup05, { minWidth: "360px" }),
  ]),
]);
