
mindmap
  root(Element as Object)
    Hooks("_on[hook]")
      _onSchedule("_onSchedule")
      _onInsert("_onInsert")
      _onBeforeUpdate("_onBeforeUpdate")
      _onUpdate("_onUpdate")
      _onMount("_onMount")
      _onBeforeRemove("_onBeforeRemove")
      _onRemove("_onRemove")
    Internal("_[internal]")
      _key("_key")
      _portal("_portal")
      _metadata("_metadata")
      _context("_context")
    Patches("$:[patches]")
    Dom("Reactive DOM")
      Tag("[tag:content]")
      Attributes("[attribute]")
      Event("[event]")
      style("style:{...}")