// AUTO-GENERATED by scripts/generate-versions.mjs — do not edit by hand.
// Regenerated on every build from packages/{core,theme,ui}/package.json.
export const CORE_VERSION = "0.19.2";
export const THEME_VERSION = "0.20.1";
export const UI_VERSION = "0.20.2";
