import {
  type DiagnoseOptions,
  type ValidationReport,
  validate,
} from "./diagnose.js";
import { findTag, isPlainObject, isRawHTML, VOID } from "./shared.js";

// Autofix for Domphy element trees. We ONLY apply transforms that are provably
// lossless — they fix structurally-invalid input without guessing intent. Every
// other diagnostic (missing/unstable keys, inline typography, literal colors,
// unknown tones/tags) needs semantic intent the tree does not carry, so applying
// a "fix" would corrupt the author's meaning (e.g. an index key is itself the
// unstable-key anti-pattern). Those are returned in `report` for the model or a
// human to resolve. The fixer set is a registry so safe transforms can be added.

// Structural clone that preserves functions (reactive `(listener) => …` values)
// by reference — a JSON clone would drop them. Primitives pass through.
// The memo map keeps shared references shared and makes circular structures
// survivable (the clone preserves the cycle instead of recursing forever).
function cloneTree(
  value: unknown,
  seen = new Map<unknown, unknown>(),
): unknown {
  if (Array.isArray(value)) {
    if (seen.has(value)) return seen.get(value);
    const out: unknown[] = [];
    seen.set(value, out);
    for (const item of value) out.push(cloneTree(item, seen));
    return out;
  }
  if (isPlainObject(value)) {
    if (seen.has(value)) return seen.get(value);
    const out: Record<string, unknown> = {};
    seen.set(value, out);
    for (const key in value) out[key] = cloneTree(value[key], seen);
    return out;
  }
  return value;
}

/** One applied lossless fix. */
export interface AppliedFix {
  rule: string;
  /** Human path to the node, e.g. "div > input". */
  path: string;
  message: string;
}

/** Result of {@link fix}: the corrected tree, what was applied, and what remains. */
export interface FixResult {
  /** A deep copy of the input with lossless fixes applied (functions preserved). */
  tree: unknown;
  /** The lossless fixes that were applied. */
  applied: AppliedFix[];
  /** validate() run on the fixed tree — `report.issues` are the manual remainder. */
  report: ValidationReport;
}

/**
 * Applies every provably-lossless fix to a copy of the tree and returns the
 * result plus a fresh validation report. Currently fixes `void-content` (a void
 * tag like input/img/br cannot have children, so its content is set to null) on
 * STATICALLY declared content. Issues that need intent are left untouched and
 * surface in `report` — this includes `raw-spacing-value` and `raw-theme-value`
 * (require semantic choices) and key rules (require stable identity from data,
 * not the tree shape). `void-content` INSIDE reactive content functions is also
 * reported but never fixed: the closure regenerates its return value on every
 * call, so mutating the evaluated result would fix nothing in the tree (and
 * would corrupt captured state the closure shares with the caller).
 */
export function fix(root: unknown, options: DiagnoseOptions = {}): FixResult {
  const tree = cloneTree(root);
  const applied: AppliedFix[] = [];
  walkFix(tree, "", applied, false, options.runReactive !== false);
  return { tree, applied, report: validate(tree, options) };
}

function walkFix(
  node: unknown,
  path: string,
  applied: AppliedFix[],
  dynamic: boolean,
  runReactive: boolean,
  seen = new Set<unknown>(),
): void {
  // Reactive content functions are evaluated with the same no-op-listener
  // pattern diagnose's walk() uses, so the fix walker sees the same nodes the
  // diagnostics were produced from. The result — and everything inside it — is
  // marked `dynamic`: it is regenerated by the closure on every call, so
  // mutating it would not persist into the returned tree. Dynamic content is
  // walked (for parity and cycle safety) but never fixed; its issues remain in
  // `report`, which keeps `applied` honest.
  if (typeof node === "function") {
    if (!runReactive) return;
    // Reactive cycle guard (same contract as walk() in diagnose.ts): a
    // function returning itself — directly or through a chain — would recurse
    // forever. Active only while the function's subtree is walked.
    if (seen.has(node)) return;
    seen.add(node);
    let result: unknown;
    try {
      result = (node as (listener: unknown) => unknown)(() => {});
    } catch {
      seen.delete(node);
      return; // reactive fn threw without a real runtime — skip
    }
    walkFix(result, path, applied, true, runReactive, seen);
    seen.delete(node);
    return;
  }

  // Cycle guard — a malformed tree can reference itself; never recurse twice
  // into the same object/array (see walk() in diagnose.ts).
  if (Array.isArray(node)) {
    if (seen.has(node)) return;
    seen.add(node);
    for (const [index, child] of node.entries()) {
      walkFix(child, `${path}[${index}]`, applied, dynamic, runReactive, seen);
    }
    return;
  }
  if (!isPlainObject(node) || isRawHTML(node)) return;
  if (seen.has(node)) return;
  seen.add(node);

  const tag = findTag(node);
  if (!tag) return;
  const here = path ? `${path} > ${tag}` : tag;

  // void-content: a void tag renders no children, so any content is invalid and
  // cannot be rendered — clearing it to null is lossless. Only applied to
  // static content: inside a reactive function the mutation would not survive
  // the closure's next evaluation, so the issue is left for `report`.
  if (
    !dynamic &&
    VOID.has(tag) &&
    node[tag] !== null &&
    node[tag] !== undefined
  ) {
    node[tag] = null;
    applied.push({
      rule: "void-content",
      path: here,
      message: `Void tag <${tag}> cannot have content — cleared to null.`,
    });
  }

  walkFix(node[tag], here, applied, dynamic, runReactive, seen);
}
